export const USER_RIGHTS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_LINKS: 'MANAGE_LINKS',
  IMPORT_LINK_LIBRARY: 'IMPORT_LINK_LIBRARY',
  MANAGE_STEAM_INSIGHT: 'MANAGE_STEAM_INSIGHT',
} as const;
